Base policy
opensource-nepal/.github pull request #1
Opened 2024-09-26 16:10 UTC by aj3sh

This is a base organization policy. Further policies can discussed and updated later.

2024-10-01 04:01 UTC, sugat009 requested changes

2024-10-01 04:01 UTC, sugat009 commented on policy/README.md
> +  - Any member can create a public repository. Admins must review the repository later and decides whether it should remain or be archived/deleted.
```suggestion
  - Any member can create a public repository. Admins must review the repository later and decide whether it should remain or be archived/deleted.
```

2024-10-01 04:01 UTC, sugat009 commented on policy/README.md
> +  - **1 Contributor**: No approval needed
```suggestion
  - **Contributors < 10**: 1 approval
```
I think every contribution and every PR should have at least 1 approval.

2024-10-01 04:10 UTC, aj3sh commented on policy/README.md
> +  - **1 Contributor**: No approval needed
Who approves when there is only one maintainer on a repo? 

This is for the initial phase, when there is single maintainer, and does the initial project work.

2024-10-01 08:52 UTC, sugat009 commented on policy/README.md
> +  - **1 Contributor**: No approval needed
Organization admins should approve in that case or there is no meaning in sending a PR. A direct push to the `main` branch should work instead. When the repo is setup then the maintainer can change the rules to not allow direct push to the `main` branch.

2024-10-01 09:02 UTC, aj3sh commented on policy/README.md
> +  - **1 Contributor**: No approval needed
Organization admins aren't responsible for approving every PRs. But direct push to the main branch should be good.

2024-11-08 04:09 UTC, sugat009 approved these changes

2024-11-08 04:11 UTC, merged